# Generated by Django 4.0.2 on 2023-11-03 21:52

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='duedate',
            name='cattle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duedate', to='main.cattle'),
        ),
    ]
