# Generated by Django 4.0.2 on 2023-11-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cattle_image_alter_duedate_cattle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duedate',
            old_name='sire',
            new_name='sire_breed',
        ),
        migrations.RemoveField(
            model_name='cattle',
            name='location',
        ),
    ]
