# Generated by Django 4.0.2 on 2023-10-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
