# Generated by Django 4.0.2 on 2023-10-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cattle_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cattle',
            old_name='Price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='cattle',
            name='weight',
        ),
    ]
