# Generated by Django 4.0.2 on 2023-10-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_price_cattle_price_remove_cattle_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cattle',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
