# Generated by Django 4.0.2 on 2023-10-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cattle_for_sale_cattle_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
