# Generated by Django 4.0.2 on 2023-10-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cattle_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
