# Generated by Django 4.0.2 on 2023-10-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cattle_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='for_sale',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
